/* pratikye Ghost Admin uzantısı — API anahtarı içermez; Ghost oturum çerezini kullanır. */
(() => {
  'use strict';
  const ROOT_ID = 'pratikye-admin-extension';
  const API = '/ghost/api/admin/';
  const VERSION = 'v6.0';
  const state = {page: 1, limit: 20, search: '', selected: null, posts: [], detail: null, busy: false};
  const esc = (v = '') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const arr = v => Array.isArray(v) ? v : String(v || '').split(/\r?\n/).map(x => x.trim()).filter(Boolean);
  const api = async (path, options = {}) => {
    const res = await fetch(API + path, {credentials:'same-origin', headers:{Accept:'application/json','Accept-Version':VERSION,...(options.body ? {'Content-Type':'application/json'}:{})}, ...options});
    const text = await res.text(); let data = null; try { data = text ? JSON.parse(text) : null; } catch {}
    if (!res.ok) throw new Error(data?.errors?.map(x => x.message).join('; ') || `Ghost API ${res.status}`);
    return data;
  };
  const root = document.createElement('div'); root.id = ROOT_ID; root.className = 'pratikye-admin-root';
  const style = document.createElement('link'); style.rel = 'stylesheet'; style.href = new URL('pratikye-admin.css', document.currentScript?.src || location.href).href; document.head.appendChild(style);
  const icon = '<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/></svg>';
  const rootButton = () => { if (document.getElementById('pratikye-admin-launcher')) return; const b=document.createElement('button'); b.id='pratikye-admin-launcher'; b.className='pratikye-admin-launcher'; b.type='button'; b.innerHTML=icon+' Tarif editörü'; b.onclick=()=>open(); (document.querySelector('[data-testid="header-actions"]')||document.querySelector('header')||document.body).appendChild(b); };
  const shell = () => { root.innerHTML = `<div class="pratikye-admin-overlay" role="dialog" aria-modal="true"><div class="pratikye-admin-dialog"><header class="pratikye-admin-dialog__head"><div><p class="pratikye-admin-eyebrow">pratikye / içerik</p><h1>Tarif editörü</h1><p class="pratikye-admin-dialog__subhead">Kaynak ayarlarını koruyarak Ghost tariflerini düzenle</p></div><button class="pratikye-admin-dialog__close" data-close aria-label="Kapat">×</button></header><div class="pratikye-admin-dialog__body" data-body></div></div></div>`; document.body.appendChild(root); root.querySelector('[data-close]').onclick=close; root.querySelector('.pratikye-admin-overlay').onclick=e=>{if(e.target===e.currentTarget) close();}; };
  const alert = (text, kind='error') => `<div class="pratikye-admin-alert pratikye-admin-alert--${kind}" role="status">${esc(text)}</div>`;
  const renderList = () => { const rows=state.posts.map(p=>`<tr><td><button class="pratikye-admin-button pratikye-admin-button--quiet" data-edit="${esc(p.id)}"><span class="pratikye-admin-table__title">${esc(p.title)}</span><span class="pratikye-admin-table__slug">${esc(p.slug)}</span></button></td><td>${esc((p.tags||[]).map(t=>t.name).find(x=>x.startsWith('cihaz:'))?.slice(6)||'—')}</td><td>${esc(p.status||'—')}</td><td>${p.updated_at?new Date(p.updated_at).toLocaleDateString('tr-TR'):''}</td></tr>`).join(''); return `<section class="pratikye-admin-card"><div class="pratikye-admin-toolbar"><label class="pratikye-admin-field pratikye-admin-field--search"><span>Tarif ara</span><input data-search value="${esc(state.search)}" placeholder="Başlık veya slug"></label><button class="pratikye-admin-button pratikye-admin-button--primary" data-search-go>Ara</button></div><div class="pratikye-admin-table-wrap"><table class="pratikye-admin-table"><thead><tr><th>Tarif</th><th>Cihaz</th><th>Durum</th><th>Güncelleme</th></tr></thead><tbody>${rows||'<tr><td colspan="4">Tarif bulunamadı.</td></tr>'}</tbody></table></div><div class="pratikye-admin-pager"><span class="pratikye-admin-pager__count">${state.posts.length} kayıt · sayfa ${state.page}</span><span><button class="pratikye-admin-button" data-prev ${state.page<=1?'disabled':''}>Önceki</button> <button class="pratikye-admin-button" data-next ${state.posts.length<state.limit?'disabled':''}>Sonraki</button></span></div></section>`; };
  const loadList = async () => { state.busy=true; body().innerHTML='<p class="pratikye-admin-muted">Tarifler yükleniyor…</p>'; try { const q=new URLSearchParams({limit:String(state.limit),page:String(state.page),include:'tags',formats:'html'}); if(state.search) q.set('filter',`title:~'${state.search.replace(/'/g,"\\'")}'`); const d=await api(`posts/?${q}`); state.posts=d.posts||[]; body().innerHTML=renderList(); bindList(); } catch(e){ body().innerHTML=alert(e.message); } finally {state.busy=false;} };
  const parseRecipe = post => { let json={}; const m=String(post.codeinjection_head||'').match(/<script[^>]*id=["']pratikye-recipe["'][^>]*>([\s\S]*?)<\/script>/i); if(m) try{json=JSON.parse(m[1])||{}}catch{}; const html=post.html||''; const sec=(name,next)=>{const re=new RegExp(`<h2[^>]*>\\s*${name}\\s*<\\/h2>([\\s\\S]*?)(?=<h2|$)`,'i');const x=html.match(re)?.[1]||'';return [...x.matchAll(/<li[^>]*>([\s\S]*?)<\/li>/gi)].map(m=>m[1].replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()).filter(Boolean)}; return {json,ingredients:sec('Malzemeler'),steps:sec('Yapılış'),post}; };
  const input = (label,key,value,wide=false) => `<label class="pratikye-admin-field${wide?' pratikye-admin-field--wide':''}"><span>${label}</span><input data-key="${key}" value="${esc(value)}"></label>`;
  const textarea = (label,key,value,wide=true) => `<label class="pratikye-admin-field${wide?' pratikye-admin-field--wide':''}"><span>${label}</span><textarea data-key="${key}">${esc(value)}</textarea></label>`;
  const renderEdit = d => { const p=d.post,j=d.json; const tags=(p.tags||[]).map(t=>t.name); const val=(k,f='')=>j[k]??f; return `<div>${alert('Kaydetme mevcut Ghost postunu günceller; yayın durumunu ve ilişkisiz etiketleri değiştirmez.','warn')}<form data-form><section class="pratikye-admin-card"><div class="pratikye-admin-card__head"><h2>Kimlik ve cihaz</h2><span class="pratikye-admin-chip">${esc(p.status)}</span></div><div class="pratikye-admin-grid">${input('Başlık','title',p.title)}${input('Slug','slug',p.slug)}${input('Cihaz','deviceId',val('deviceId',tags.find(x=>x.startsWith('cihaz:'))?.slice(6)||''))}${input('Kategori','category',val('category',tags.find(x=>x.startsWith('kategori:'))?.slice(9)||''))}${input('Porsiyon','servings',val('servings'))}${input('Program','program',val('program'))}${input('Süre (dakika)','timeMinutes',val('timeMinutes'))}${input('Sıcaklık','temperature',val('temperature'))}${input('Aksesuar','accessories',Array.isArray(val('accessories'))?val('accessories').join(', '):val('accessories'))}</div>${textarea('Açıklama','description',p.custom_excerpt||val('description'))}</section><section class="pratikye-admin-card"><div class="pratikye-admin-card__head"><h2>Tarif gövdesi</h2></div><div class="pratikye-admin-grid">${textarea('Malzemeler — satır başına','ingredients',d.ingredients.join('\n'))}${textarea('Yapılış — satır başına','steps',d.steps.join('\n'))}${textarea('İpucu','tip',val('tip'))}${textarea('Besin değerleri','nutrition',val('nutrition'))}</div></section><section class="pratikye-admin-card pratikye-admin-card--tomato"><h2>Güvenlik önizlemesi</h2><p class="pratikye-admin-muted">Kaydetmeden önce üretilecek HTML aşağıda görünür. Bilinmeyen bloklar korunamadığında kaydetme durdurulur.</p><pre class="pratikye-admin-preview" data-preview></pre><label class="pratikye-admin-checkbox"><input type="checkbox" data-confirm> HTML önizlemesini inceledim; bu tarifte desteklenmeyen özel blok yok.</label></section><div class="pratikye-admin-actions pratikye-admin-actions--end"><button type="button" class="pratikye-admin-button" data-back>Listeye dön</button><button type="submit" class="pratikye-admin-button pratikye-admin-button--primary">Taslağı güncelle</button></div></form></div>`; };
  const makeHtml = (v, original) => { const safe=x=>esc(x).replace(/\n/g,'<br>'); return `<p>${safe(v.description)}</p><h2>Malzemeler</h2><ul>${arr(v.ingredients).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>Yapılış</h2><ol>${arr(v.steps).map(x=>`<li>${esc(x)}</li>`).join('')}</ol><h2>Cihaz ayarları</h2><ul><li>Program: ${esc(v.program)}</li><li>Süre: ${esc(v.timeMinutes)} dakika</li><li>Sıcaklık: ${esc(v.temperature)}</li><li>Porsiyon: ${esc(v.servings)}</li><li>Aksesuar: ${esc(v.accessories)}</li></ul>${v.tip?`<h2>pratikye ipucu</h2><p>${safe(v.tip)}</p>`:''}${v.nutrition?`<h2>Besin değerleri</h2><p>${safe(v.nutrition)}</p>`:''}`; };
  const bindEdit = () => { const form=root.querySelector('[data-form]'); const update=()=>{const v={};form.querySelectorAll('[data-key]').forEach(x=>v[x.dataset.key]=x.value);root.querySelector('[data-preview]').textContent=makeHtml(v);}; form.oninput=update; update(); root.querySelector('[data-back]').onclick=()=>loadList(); form.onsubmit=async e=>{e.preventDefault(); const ok=root.querySelector('[data-confirm]'); if(!ok.checked){root.querySelector('[data-preview]').insertAdjacentHTML('beforebegin',alert('Önizlemeyi onaylayın.'));return;} const v={};form.querySelectorAll('[data-key]').forEach(x=>v[x.dataset.key]=x.value); const d=state.detail; const json={...d.json,...v,timeMinutes:v.timeMinutes?Number(v.timeMinutes):null,accessories:arr(v.accessories)}; const rawJson=JSON.stringify(json,null,2).replace(/<\/script/gi,'<\\/script'); const head=String(d.post.codeinjection_head||'').replace(/(<script[^>]*id=["']pratikye-recipe["'][^>]*>)[\s\S]*?(<\/script>)/i,`$1\n${rawJson}\n$2`); try{const payload={posts:[{title:v.title,slug:v.slug,custom_excerpt:v.description,html:makeHtml(v),codeinjection_head:head,updated_at:d.post.updated_at,status:d.post.status,tags:d.post.tags}]}; await api(`posts/${encodeURIComponent(d.post.id)}/?source=html`,{method:'PUT',body:JSON.stringify(payload)}); body().innerHTML=alert('Tarif güncellendi.','success'); setTimeout(loadList,700);}catch(e){body().innerHTML=alert(e.message);}}; };
  const openEdit=async id=>{body().innerHTML='<p class="pratikye-admin-muted">Tarif açılıyor…</p>';try{const d=await api(`posts/${encodeURIComponent(id)}/?formats=html,lexical&include=tags`);state.detail=parseRecipe(d.posts[0]);body().innerHTML=renderEdit(state.detail);bindEdit();}catch(e){body().innerHTML=alert(e.message);}};
  const bindList=()=>{root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit));root.querySelector('[data-search-go]').onclick=()=>{state.search=root.querySelector('[data-search]').value.trim();state.page=1;loadList()};root.querySelector('[data-prev]').onclick=()=>{state.page--;loadList()};root.querySelector('[data-next]').onclick=()=>{state.page++;loadList()};};
  const body=()=>root.querySelector('[data-body]'); const open=()=>{shell();loadList();}; const close=()=>{root.remove();};
  const mount=()=>{rootButton();}; new MutationObserver(mount).observe(document.body,{childList:true,subtree:true}); mount();
})();
